// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC58zEaWy2PNWwpNxiCEJecNHrqHFrd2iE',
    appId: '1:104119772783:web:f6702ac813f3e7acb24f9a',
    messagingSenderId: '104119772783',
    projectId: 'tripledger-ebc18',
    authDomain: 'tripledger-ebc18.firebaseapp.com',
    storageBucket: 'tripledger-ebc18.firebasestorage.app',
    measurementId: 'G-GMB6ZWN7J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNjuHa34buLWoow79a5Di8-E0o6rnCh2c',
    appId: '1:104119772783:android:9db791b026a93a36b24f9a',
    messagingSenderId: '104119772783',
    projectId: 'tripledger-ebc18',
    storageBucket: 'tripledger-ebc18.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7UIG8o27EJqxsV7AFdeo45pMWvF4532c',
    appId: '1:104119772783:ios:492b1854f30bea3db24f9a',
    messagingSenderId: '104119772783',
    projectId: 'tripledger-ebc18',
    storageBucket: 'tripledger-ebc18.firebasestorage.app',
    iosBundleId: 'com.example.tripapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7UIG8o27EJqxsV7AFdeo45pMWvF4532c',
    appId: '1:104119772783:ios:492b1854f30bea3db24f9a',
    messagingSenderId: '104119772783',
    projectId: 'tripledger-ebc18',
    storageBucket: 'tripledger-ebc18.firebasestorage.app',
    iosBundleId: 'com.example.tripapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC58zEaWy2PNWwpNxiCEJecNHrqHFrd2iE',
    appId: '1:104119772783:web:02d0c2073b0b2213b24f9a',
    messagingSenderId: '104119772783',
    projectId: 'tripledger-ebc18',
    authDomain: 'tripledger-ebc18.firebaseapp.com',
    storageBucket: 'tripledger-ebc18.firebasestorage.app',
    measurementId: 'G-R0E2VVGGPL',
  );
}
